# -*- coding: utf-8 -*-
from . import partner
from . import product
from . import ngo_sponsor
from . import ngo_beneficiary
from . import ngo_guide
from . import ngo_association
from . import ngo_settings
from . import ngo_application
from . import ngo_document
from . import ngo_distribution
from . import ngo_distribution_schedule
from . import ngo_standard_report_template
from . import ngo_distribution_food_portion_report
from . import ngo_distribution_food_report
from . import ngo_distribution_clothes_report
from . import ngo_distribution_receiving
from . import res_config_settings
from . import application_type
